### ISSUE TITLE
Docs should recommend creating a new GCP project?

### ISSUE THREAD

**Issue by zstumgoren** [associatedpress/harvester#8]
AFAICT a GCP project can only have one Oauth consent form. If another app is configured to use Oauth in a user's sole GCP project, it means Harvester would need to share that same form. This appears to be possible (i.e. you can add multiple Redirect URIs and Authorized domains), but I believe they would need to share the same user verification screen and related metadata about user policy, etc.

Might be a good idea to instruct users to create a new GCP project specifically for Harvester.

**Comment by andrewmilligan** [comment]
Yes this is a great point. The new version of the docs recommend creating a new project so I'm going to close this:

https://harvester.readthedocs.io/en/latest/google_credentials/#google-cloud-platform-project
